import { BaseTheme, createTheme } from '@shopify/restyle'

const theme = createTheme({
  colors: {
    purpleLight: '#8C6FF7',
    purplePrimary: '#5A31F4',
    purpleDark: '#3F22AB',

    greenLight: '#56DCBA',
    greenPrimary: '#0ECD9D',
    greenDark: '#0A906E',

    black: '#0B0B0B',
    white: '#F0F2F3',
    gray: '#9DA3B4',

    primary: '#406836',
    surfaceTint: '#406836',
    onPrimary: '#FFFFFF',
    primaryContainer: '#C0EFB0',
    onPrimaryContainer: '#002200',
    secondary: '#54634D',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#D7E8CD',
    onSecondaryContainer: '#121F0E',
    tertiary: '#386568',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#BCEBEE',
    onTertiaryContainer: '#002022',
    error: '#BA1A1A',
    onError: '#FFFFFF',
    errorContainer: '#FFDAD6',
    onErrorContainer: '#410002',
    background: '#F8FBF1',
    onBackground: '#191D17',
    surface: '#F8FBF1',
    onSurface: '#191D17',
    surfaceVariant: '#DFE4D7',
    onSurfaceVariant: '#43483F',
    outline: '#73796E',
    outlineVariant: '#C3C8BC',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#2E322B',
    inverseOnSurface: '#EFF2E8',
    inversePrimary: '#A5D395',
    primaryFixed: '#C0EFB0',
    onPrimaryFixed: '#002200',
    primaryFixedDim: '#A5D395',
    onPrimaryFixedVariant: '#285020',
    secondaryFixed: '#D7E8CD',
    onSecondaryFixed: '#121F0E',
    secondaryFixedDim: '#BBCBB2',
    onSecondaryFixedVariant: '#3C4B37',
    tertiaryFixed: '#BCEBEE',
    onTertiaryFixed: '#002022',
    tertiaryFixedDim: '#A0CFD2',
    onTertiaryFixedVariant: '#1E4D50',
    surfaceDim: '#D8DBD2',
    surfaceBright: '#F8FBF1',
    surfaceContainerLowest: '#FFFFFF',
    surfaceContainerLow: '#F2F5EB',
    surfaceContainer: '#ECEFE5',
    surfaceContainerHigh: '#E6E9E0',
    surfaceContainerHighest: '#E1E4DA',
  },
  spacing: {
    xs: 4,
    s: 8,
    m: 16,
    l: 24,
    xl: 32,
  },
  breakpoints: {
    phone: 0,
    longPhone: {
      width: 0,
      height: 812,
    },
    tablet: 768,
    largeTablet: 1024,
  },
  borderRadii: {
    xss: 2,
    xs: 4,
    s: 8,
    m: 16,
    l: 24,
    xl: 32,
  },
  textVariants: {
    'display/large': {
      fontSize: 57,
      fontFamily: 'MontserratAlternates-Regular',
      lineHeight: 64,
      letterSpacing: -0.25,
    },
    'display/medium': {
      fontSize: 45,
      fontFamily: 'MontserratAlternates-Regular',
      lineHeight: 52,
      letterSpacing: 0,
    },
    'display/small': {
      fontSize: 36,
      fontFamily: 'MontserratAlternates-Regular',
      lineHeight: 44,
      letterSpacing: 0,
    },
    'headline/large': {
      fontSize: 32,
      fontFamily: 'MontserratAlternates-Regular',
      lineHeight: 40,
      letterSpacing: 0,
    },
    'headline/medium': {
      fontSize: 28,
      fontFamily: 'MontserratAlternates-Regular',
      lineHeight: 36,
      letterSpacing: 0,
    },
    'headline/small': {
      fontSize: 24,
      fontFamily: 'MontserratAlternates-Regular',
      lineHeight: 32,
      letterSpacing: 0,
    },
    'body/large': {
      fontSize: 16,
      fontFamily: 'MontserratAlternates-Regular',
      lineHeight: 24,
      letterSpacing: 0.5,
    },
    'body/medium': {
      fontSize: 14,
      fontFamily: 'MontserratAlternates-Regular',
      lineHeight: 20,
      letterSpacing: 0.25,
    },
    'body/small': {
      fontSize: 12,
      fontFamily: 'MontserratAlternates-Regular',
      lineHeight: 16,
      letterSpacing: 0.4000000059604645,
    },
    'label/large': {
      fontSize: 14,
      fontFamily: 'MontserratAlternates-Bold',
      lineHeight: 20,
      letterSpacing: 0.10000000149011612,
    },
    'label/medium': {
      fontSize: 12,
      fontFamily: 'MontserratAlternates-Bold',
      lineHeight: 16,
      letterSpacing: 0.5,
    },
    'label/small': {
      fontSize: 11,
      fontFamily: 'MontserratAlternates-Bold',
      lineHeight: 16,
      letterSpacing: 0.5,
    },
    'title/large': {
      fontSize: 22,
      fontFamily: 'MontserratAlternates-SemiBold',
      lineHeight: 28,
      letterSpacing: 0,
    },
    'title/medium': {
      fontSize: 16,
      fontFamily: 'MontserratAlternates-Medium',
      lineHeight: 24,
      letterSpacing: 0.15000000596046448,
    },
    'title/small': {
      fontSize: 14,
      fontFamily: 'MontserratAlternates-Medium',
      lineHeight: 20,
      letterSpacing: 0.10000000149011612,
    },

    defaults: {
      fontSize: 14,
      fontFamily: 'MontserratAlternates-Regular',
      lineHeight: 20,
      letterSpacing: 0.25,
    },
  },
})

export type Theme = typeof theme
export default theme
